### ISSUE TITLE
Store password hash instead of clear texts

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#1]

**Comment by HuangBohan** [comment]
https://www.railstutorial.org/book/modeling_users#sec-adding_a_secure_password

**Comment by Melvin-Tan** [comment]
For this one, can shun bian include the minimum length of password to be 6(or 8)? =P
validates :password, presence: true, length: {minimum: 6}
I think this is the syntax, but I don't feel like making this breaking change for now lol
