### ISSUE TITLE
Server respond 204 when calling wishes create api

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#10]
The payload is actually added in the database, because I can find them later when I pull all wishes from user. Just the response code seems incorrect

**Comment by Melvin-Tan** [comment]
Hmmm I can't replicate that. All I get is 200 even for validation errors (btw title must be at least 5 characters, description is optional)

**Comment by null09264** [comment]
Oh okay, I didn't know the 5 character limit, will try again and get back to this

**Comment by Melvin-Tan** [comment]
Basically I trying to enforce at least have title lor.. I believe front-end validation does that too.
