### ISSUE TITLE
Wishes table requires extra fields

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#11]
- [x] hasMeetUpAddress (boolean)
- [x] addressDescription (string)
- [x] latitude (double)
- [x] longitude (double)

-----------------

**In the response, server should give**

1. Whether the post is successful
2. If so, the updated points user has after posting
3. If not, the reason (such as, not enough points)

-----------------
Some example payload when frontend doing the request:

when `needs_meetup` attribute is `false`
```
{
    description : "Description-7"
    title : "Title-7"
    needs_meetup : false
}
```

or when `needs_meetup` attribute is `true`
```
{
    description : "Description-8"
    title : "Title-8"
    needs_meetup : true
    latitude : 1.3521
    longitude : 103.81979999999999
    address_line : "114 Windsor Park Rd, Singapore 574178"
}
```

**Comment by Melvin-Tan** [comment]
{
    description : "Description-8"
    title : "Title-8"
    needs_meetup : true
    latitude : 1.3521
    longitude : 103.81979999999999
    address_line : "114 Windsor Park Rd, Singapore 574178"
}

Should I validate that ALL latitude and longitude and address_line is PRESENT when needs_meetup is true?

**Comment by null09264** [comment]
Okay

**Comment by Melvin-Tan** [comment]
"""In the response, server should give

Whether the post is successful
If so, the updated points user has after posting
If not, the reason (such as, not enough points)"""

We might need to iron out the points system...
