### ISSUE TITLE
Wishes response need one more attribute

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#12]
when front-end request all wishes from the user, one more attribute for each wish inside is required:

- [x] wisherHasContact (boolean), which is true when the wisher's hand phone number is not null

**Comment by Melvin-Tan** [comment]
Does it make more sense if I just add a column for contact-number as a string, then u just decide whether contact exist or is null?

**Comment by null09264** [comment]
Yeah, the concern is about security (privacy?). We don't want the user get the contact number before they accept a wish

**Comment by Melvin-Tan** [comment]
Noted. Boolean it shall be

**Comment by Melvin-Tan** [comment]
This affects which action btw?
All the GET related to wish right?

**Comment by Melvin-Tan** [comment]
OK DONE! Wait for bohan push
