### ISSUE TITLE
Get User Wishes should return the ones that this user has helped others to fulfil

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#13]
Instead of an array, front end expects the data to be: 
``` json

{
    "self": [{...}, {...}, {...}],
    "others": [{...}, {...}, {...}]
}

```

**Comment by Melvin-Tan** [comment]
For self its already what I've done, so this question is on "others"

Do you want only fulfilled wishes, or any wish that is assigned to the user? It's all wish that is assigned to user right?

**Comment by null09264** [comment]
Oh right, any wish that is assigned to the user is more reasonable. Furthermore, the user's token should be granted access to these wishes as well.

**Comment by Melvin-Tan** [comment]
I'll arrow bohan to handle the part on token. Otherwise I've already push it to master. :)
