### ISSUE TITLE
Sign up: pass in existing username gives 422 response.

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#3]
expected behaviors:

- [x] When the sign up is successful, response message should be "SUCCESS" instead of just an empty 200 message

- [x] When the sign up is unsuccessful, response message should contain the reason, "Username already existed"

**Comment by Melvin-Tan** [comment]
Response message is success: "Created User" (same for create report)

When unsuccessful it is exception: "Username is already taken". There is a validation for it that automatically throws this exception

**Comment by null09264** [comment]
Okay, so the 422 response is made purposely?

**Comment by Melvin-Tan** [comment]
{
  "status": 422,
  "error": "Unprocessable Entity",
  "exception": "#<ActiveRecord::RecordInvalid: Validation failed: Username has already been taken>",
}

Ya it's rails way of saying the validation failed.


Should I just change all the errors to exceptions? (Like "No such user" is currently an error, while those auto generated ones are exceptions) that might make it easier for you guys where all success is under success, all failures is under exception

**Comment by null09264** [comment]
Okay, then leave it as is. The only problem is currently we are not able to catch the exception message, but if there's only one kinds of exception, shouldn't be a big problem. Let's just keep it this way until we have some spare time.
