### ISSUE TITLE
APIs needed

### ISSUE THREAD

**Issue by null09264** [Wishes-CS3216/Wishes-Backend#5]
**This is a check list for the APIs required**

- [x] **user password update** (param: `username, oldPassword, newPassword`)
- [x] **user info update** (param: `user`, which is a JSON object contains all the fields in user table)
- [ ] _LOW PRIORITY_ **forget password** (param: `username`, a response indicating success or failure is required). Server should send an email with a randomly generated new password to the users email. If user has no email, failure should be echoed back.

- [x] _LOW PRIORITY_ **leaderboard** (no param) return top ten for being helper and helping others

Please don't close this issue, we may write all needed APIs in this post in the future.

**Comment by Melvin-Tan** [comment]
Sorry if I get this wrong ahh.. The param: something something is that the input you will give, or is that the output you want? (or different for each of them?)

**Comment by null09264** [comment]
The input we will give

**Comment by Melvin-Tan** [comment]
User info update is done
https://docs.google.com/document/d/1Dv9X8xhyWzRxw0uSFKZjSvgvuPcaPthfdKTPAymEv9g/edit
Check out the format for the json needed in the google docs documentation.
Use the 'application/json' thingy to PUT the user params.
